### ISSUE TITLE
Getting error on build

### ISSUE THREAD

**Issue by jagehring** [talamortis/mod_reward_shop#12]
/azerothcore-wotlk/modules/mod_reward_shop/src/reward_shop.cpp:40:17: fatal error: no member named 'ADD_GOSSIP_ITEM_EXTENDED' in 'Player'
 
player->ADD_GOSSIP_ITEM_EXTENDED(GOSSIP_ICON_CHAT, "I'd like to redeem my code.", GOSSIP_SENDER_MAIN, 1, text, 0, true);

**Comment by talamortis** [comment]
fixed with latest pull from azerothcore
